### ISSUE TITLE
Allow for commands to be executed on rebuild

### ISSUE THREAD

**Issue by peacememories** [tomekwi/elm-live#67]
Hi, and first of all thanks for this wonderful tool :)

It would be nice to be able to specify a command that is run every time the code is rebuilt (ideally before the live-reload)

This would allow people to use tools like elm-css with the dev server, running the elm-css command every time the code changes.

**Comment by tomekwi** [comment]
Hey, great idea! I’ve been thinking about this myself 🙂

It’s very likely I’ll be setting up another project with elm-live soon – if that’s the case, I’ll surely extend elm-live to cover this.

Until then, I’m afraid I can’t do much to make this happen myself – a PR would be much appreciated though 😀

**Comment by peacememories** [comment]
I'm looking into writing a PR, and I've got a few questions :)
* Is it okay to put the code into the build() function? Seems to be the place to put it from my perspective
* `cross-spawn` doesn't seem to implement an exec-function (point being to supply a full command with the `--on-build` option. Are there any objections to adding child_process? Alternative would be to manually extract the executable name and arguments)

**Comment by tomekwi** [comment]
Hey Gabriel, thanks a lot for your help and enthusiasm! As for your questions,

> Is it okay to put the code into the build() function? Seems to be the place to put it from my perspective

Yep, seems like the right place to put it. I’ve been doing my best to make any error messages as helpful and beautiful as possible (in line with the compiler). Please look around and try to match the output in tone and style.

> `cross-spawn` doesn't seem to implement an exec-function (point being to supply a full command with the `--on-build` option. Are there any objections to adding child_process? Alternative would be to manually extract the executable name and arguments)

`cross-spawn` came there as we introduced Windows support. I can’t remember what the reason was that `child_process` (which I had used previously) didn’t bite it. @bdukes may have more context than I do. If you need an answer now, your best bet would be to look at [related PRs and issues](https://github.com/tomekwi/elm-live/issues?utf8=%E2%9C%93&q=windows%20NOT%20greenkeeper).

**Comment by tomekwi** [comment]
Of course, if you have any more question, I’ll be more than happy to help 🙂

**Comment by bdukes** [comment]
@peacememories, the main thing that we're getting from `cross-spawn` is escaping arguments and using default extensions (e.g. finding `elm-make.cmd` when I ask to run `elm-make`).  If you're passing in a command line yourself, I'd be okay with that going through `child_process.exec`, since individual users can control how they're passing that argument (e.g. adding `.cmd` manually).

Hope it helps!

**Comment by peacememories** [comment]
@bdukes thanks for the answer :) Then I'll implement it using child_process for the time being I think.

**Comment by peacememories** [comment]
I think I'll move discussion on how to implement this into a WIP pull request if that's okay with you.

**Comment by tomekwi** [comment]
👍 Thanks for your help so far!
