### ISSUE TITLE
Windows support - help doesn't work

### ISSUE THREAD

**Issue by bdukes** [tomekwi/elm-live#7]
Running `elm-make --help` in Windows doesn't do anything, since it's shelling out to `man`, which is a *nix program.

**Comment by tomekwi** [comment]
Thanks for reporting! Do you use `cmd` or a Unix-flavored shell like Git Bash or cygwin?

While I don’t have a windows box to test this, I remember calling `git help …` or `npm help …` in Git Bash (which is basically [msys](http://www.mingw.org/wiki/msys)) on friends’ computers. Both commands worked by displaying the manpage rendered as HTML in a browser. Both commands spawn `man` under the hood

A Windows alternative to man compatible with manpage files seems to be the best path forward. But since the manpage is just rendered from the readme, we could also render a plain text fallback from the same source.

**Comment by bdukes** [comment]
I typically use PowerShell, but even using the bash or mintty shells that come with Git, I get an error that "man" is not recognized.

I believe `git help` just opens pre-rendered HTML, I don't think it's processing a manfile in real time.

**Comment by tomekwi** [comment]
Alright, I believe the only reasonable thing is to render a plain text fallback then. I’ll try to tackle this on Wendesday – I’m afraid I won’t have time before then.
